FROM <%= base_image %>
MAINTAINER <%= author['name'] %> <%= author['email'].inspect %>

ARG docker_engine_version
ARG docker_compose_version
ARG docker_gid
ARG docker_group
ARG luban_uid
ARG luban_user
ARG luban_root_path

# Install required tools and libraries
RUN yum -y install \
        <%= base_packages.join(" \\\n        ") %> && \
    yum clean all && \
    \
    # Create docker group with the given docker gid
    groupadd -g $docker_gid $docker_group && \
    \
    # Install docker engine
    yum -y install yum-utils && \ 
    yum-config-manager --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo && \
    yum makecache fast && yum -y install docker-ce-$docker_engine_version && \
    yum clean all && \
    \
    # Install docker compose
    curl -L "https://github.com/docker/compose/releases/download/$docker_compose_version/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

# Create luban user with the given luban uid
# Adding luban user to the ftp group is to walk around an issue in mounting docker socket in OSX
RUN adduser -ms /bin/bash -u $luban_uid -G docker,ftp $luban_user && \
    echo "source <%= app_path.join(".luban_profile") %>" >> /home/$luban_user/.bashrc && \
    mkdir -p $luban_root_path && \
    mkdir -p <%= deployment_projects_path %> && \
    mkdir -p <%= downloads_path %> && \
    mkdir -p <%= docker_root_path %> && \
    mkdir -p <%= packages_root_path %> && \
    mkdir -p <%= releases_root_path %> && \
    mkdir -p <%= env_path %> && \
    mkdir -p <%= tmp_path %> && \
    chown -R $luban_user:$luban_user $luban_root_path

# Add application archives
ADD <%= build[:archives].collect { |_, a| a[:path].basename }.join(" \\\n    ") %> /

# RUN chown -R $luban_user:$luban_user $luban_root_path

# Populate image labels
LABEL luban.project="<%= project %>" \
      luban.application="<%= project %>" \
      luban.stage="<%= stage %>" \
      <%- build[:sources].each_pair do |name, source| -%>
      luban.<%= name %>.source_tag="<%= source[:tag] %>" \
      <%- end -%>
      luban.build_tag="<%= build_tag %>" \
      luban.bulid_rev="<%= build[:revision] %>" \
      <%- get_packages.each_pair do |name, package| -%>
      <%- package.each_pair do |k, v| -%>
      luban.packages.<%= name %>.<%= k %>="<%= v %>" \
      <%- end -%>
      <%- end -%>
      luban.docker_engine="$docker_engine_version" \
      luban.docker_compose="$docker_compose_version" \
      luban.docker_gid="$docker_gid" \
      luban.docker_group="$docker_group" \
      luban.luban_uid="$luban_uid" \
      luban.luban_user="$luban_user" \
      luban.luban_root_path="$luban_root_path"

USER $luban_user
WORKDIR /home/$luban_user

CMD ["/bin/bash"]
